seetings_default_param = {
    "consumer_based_on_tariff": False,
    "consumer_connection_limit": False,
    "solver_name": "gurobi",
    "flex_dem_active_for_consumer": True,
    "t_start": 6553,
    "t_end": 6552,
    "Node_list_all": [
        "CH00",
        "ITCN",
        "ITCS",
        "ITN1",
        "ITS1",
        "ITSA",
        "ITSI",
        "DE00",
        "DEKF"
        "FR00",
        "AT00",
        "DKE1",
        "DKW1",
        "DKKF",
        "BE00",
        "CZ00",
        "ES00",
        "UK00",
        "HU00",
        "LU00",
        "NL00",
        "PL00",
        "PT00",
        "SI00",
        "SK00",
        "HR00",
        "SE01",
        "SE02",
        "SE03",
        "SE04",
        "NON1",
        "NOM1",
        "NOS0",
    ],
    "Node_list": [        
        "CH00",
        "ITCN",
        "ITCS",
        "ITN1",
        "ITS1",
        "ITSA",
        "ITSI",
        "DE00",
        "FR00",
        "AT00",
        "DKE1",
        "DKW1",
        "DKKF",
        "BE00",
        "CZ00",
        "ES00",
        "UK00",
        "HU00",
        "LU00",
        "NL00",
        "PL00",
        "PT00",
        "SI00",
        "SK00",
        "HR00",
        "SE01",
        "SE02",
        "SE03",
        "SE04",
        "NON1",
        "NOM1",
        "NOS0",
    ],
    "weather_year": 1982,
    "run_year": 2040,
    "eu_policy": "NT",
    "ch_policy": "WWB",
    "consumer_start": 1,
    "consumer_end": 300,
    "opt_mode": "core",
    "consumers_representing": 8230,
    "slack_soc": False,
    "single_large_battery": True,
    "winter_limit":{
        "mode": False,
        "window": [7297, 2185],
        "energy_MWh": 10*1000000
        }, 
    "rep_hydro_plants": True,
    "res_investment_allowed": False,
    "NTC_CH_ratio": 1,
}


